### ISSUE TITLE
How to correctly resolve imports in a protobuf file?

### ISSUE THREAD

**Issue by renjithgr** [redpanda-data/connect#1325]
I am trying to dump the data from a Kafka topic to a table using Benthos. The messages are protobuf encoded. I am trying to use the Benthos protobuf processor. I am getting the following error when I try to run it.

```
ERRO Service closing due to: failed to init processor <no label> path root.pipeline.processors.0: failed to parse .proto file: record.proto:5:8: open proto/google/protobuf/datetime.proto: no such file or directory  @service=benthos
```

I am importing `google/protobuf/datetime.proto` in the protobuf file. What is the right way to include protobuf imports coming from other libraries, in this case Google library?

**Comment by mihaitodor** [comment]
Hey @renjithgr, thanks for trying out the protobuf functionality! You'll need to enumerate all folders including transitive dependencies that contain `.proto` files under https://www.benthos.dev/docs/components/processors/protobuf#import_paths when configuring the `protobuf` processor. Otherwise, Benthos won't be able to find them...

There might be some tool that can produce an amalgamation of all these dependencies as a single large `.proto` file, but I can't find one based on a quick search.

**Comment by renjithgr** [comment]
@mihaitodor Thanks for the reply. I was able to get it to work.
