### ISSUE TITLE
 require breaking the codebase out into several individual modules

### ISSUE THREAD

**Issue by luxixing** [redpanda-data/connect#1332]
benthos version: v4(main)

I want to just import pure so that I can use service to build streams without relying on external infrastructure like gcp aws. Now all components are still imported by default,
example
```
"github.com/benthosdev/benthos/v4/public/service
```
I  understand that importing public/components/all in public/service is not necessary, maybe public/components/pure is sufficient for example or test.
when I go mod tidy, it will report the error
```
go: finding module for package google.golang.org/grpc/credentials/insecure
git-biz.qianxin-inc.cn/skylar-ng/skylar-common/hermes/hermes-service.git/pkg/benthos/input imports
        github.com/benthosdev/benthos/v4/public/service tested by
        github.com/benthosdev/benthos/v4/public/service.test imports
        github.com/benthosdev/benthos/v4/public/components/all imports
        github.com/benthosdev/benthos/v4/internal/impl/gcp imports
        github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace tested by
        github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace.test imports
        google.golang.org/grpc/credentials/insecure: module google.golang.org/grpc@latest found (v0.0.0-00010101000000-000000000000, replaced by google.golang.org/grpc@v1.26.0), but does not contain package google.golang.org/grpc/credentials/insecure
```
@Jeffail

**Comment by Jeffail** [comment]
Just to clarify these dependencies won't be compiled into your resulting binary, but they're included in the dependency tree since we have a single go.mod file at the root of the repo. The specific issue here appears to be a `replace` directive that is breaking transitive dependencies.

In order to avoid this we will need to break `./public/service` out into its own go module, along with each individual `./public/components` package. I'm not sure what impact that will have on development, maybe use workspaces? https://go.dev/doc/tutorial/workspaces

**Comment by mihaitodor** [comment]
I think we can close this for now. We have the bundles here https://github.com/redpanda-data/connect/tree/main/public/bundle and, also, the Benthos framework is a separate repo now: https://github.com/redpanda-data/benthos.
