### ISSUE TITLE
4.28.0 should really be 5.0.0

### ISSUE THREAD

**Issue by chenrui333** [redpanda-data/connect#2620]
Since the artifact got changed and everything got renamed from benthos to connect, it should be really 5.0.0 rather than 4.28.0

relates to https://github.com/Homebrew/homebrew-core/pull/173310

**Comment by chenrui333** [comment]
that would also help surfacing the engine split and license changes

**Comment by Jeffail** [comment]
Hey @chenrui333, sorry this fell off the radar in relation to how it would impact homebrew. I was operating under the mindset of Go module versioning, and since we have a new module name we're an entirely new module with no compatibility guarantees across the old (although in practice we are keeping the Go APIs compatible).

The official builds of Redpanda Connect are bundled with distributions of Redpanda itself, so we're going to be releasing under rpk (https://docs.redpanda.com/current/get-started/rpk-install/). I'm not sure what the best approach would be for homebrews benthos installer, but I think it'd be best to freeze it at 4.27.0 as there's no intention of making official releases of a standalone benthos binary in future.

**Comment by chenrui333** [comment]
it is really less about homebrew, but more of user information (obviously in this case, it would be homebrew formula update).

Once I learned that the engine got spun off into a separate repo, it is easy to navigate in the brew side. 

close the issue for now.
