### ISSUE TITLE
Add connector support levels to the connector source and templates

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/connect#2684]
Update the Go templates so that each connector gets an Asciidoc attribute with its support level. We should have support levels for all inputs, outputs, and processors. As well as individual support levels for database drivers and caches. Also, could you update the [templating guide](https://docs.redpanda.com/redpanda-connect/configuration/templating/) with any new fields?

**Comment by Feediver1** [comment]
@Jeffail Docs is working on a release process for connector docs. We have 2 requirements for each connector to be included in the docs:
- version in which connector is added
- support level (community or certified)
Without both, a connector will not be included in the docs. So that we can proceed with implementing this process, can you clarify when this ticket will be implemented? Thanks.

**Comment by JakeSCahill** [comment]
This data is now available in the CSV
