### ISSUE TITLE
Input/Output linting prevents usage of Environment Variables

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [redpanda-data/connect#3047]
When having Linting like in: https://github.com/redpanda-data/connect/blob/5a64fed7c09746f1591d26ce350f2787ca6cae62/internal/impl/kafka/input_kafka_franz.go#L61

it forces Unit-Testing to fail since at lint time, the Environment Variables are not yet set and then in turn the lint check fails.
This change broke some of our pipelines recently.

**Comment by mihaitodor** [comment]
Hey @AndreasBergmeier6176, thanks for raising that! Would it be possible for you to set a default value for your environment variables? For example `${CONSUMER_GROUP:whatever}` (you can also do `${FOOBAR:}` if an empty string is a valid default value)? Otherwise, it would be really difficult to come up with a selective linting scheme for tests which is somehow different than the linting scheme used outside of tests.
